CREATE TABLE schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 ID',
    title VARCHAR(100) NOT NULL COMMENT '일정 제목',
    username VARCHAR(50) NOT NULL COMMENT '작성자 이름',
    password VARCHAR(255) NOT NULL COMMENT '비밀번호',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    modifiedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);
