CREATE TABLE SCHEDULE
(
    scheduleId  BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 ID',
    userId      BIGINT NOT NULL COMMENT '사용자 ID',
    title       VARCHAR(100) NOT NULL COMMENT '일정 제목',
    content     VARCHAR(255) COMMENT '일정 내용',
    password    VARCHAR(255) NOT NULL COMMENT '비밀번호',
    createAt    DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updateAt    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    FOREIGN KEY (userId) REFERENCES USER(userId) ON DELETE CASCADE
);