spring:
  application:
    name: SchedulerProject
# 데이터 소스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/schedule
    username: root
    password: ekdls0901
    driver-class-name: com.mysql.cj.jdbc.Driver